/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#adc6ff',
        tertiary: '#005ac2',
        'on-surface-variant': '#3c4a42',
        'tertiary-container': '#71a1ff',
        'inverse-primary': '#4edea3',
        'tertiary-fixed': '#d8e2ff',
        'on-surface': '#0e1f17',
        'on-primary-container': '#00422b',
        'on-primary': '#ffffff',
        'primary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#00513b',
        outline: '#6c7a71',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbdfd2',
        'surface-container': '#def3e6',
        error: '#ba1a1a',
        'surface-variant': '#d3e7db',
        'outline-variant': '#bbcabf',
        'secondary-fixed-dim': '#8bd6b6',
        'on-error': '#ffffff',
        'secondary-container': '#a6f2d1',
        'on-secondary-container': '#237157',
        'on-background': '#0e1f17',
        surface: '#eafef1',
        secondary: '#1b6b51',
        'inverse-on-surface': '#e1f6e9',
        'surface-container-high': '#d9ede0',
        'surface-container-low': '#e4f9ec',
        primary: '#006c49',
        'primary-container': '#10b981',
        'on-primary-fixed-variant': '#005236',
        'on-secondary': '#ffffff',
        'surface-bright': '#eafef1',
        'on-primary-fixed': '#002113',
        'primary-fixed-dim': '#4edea3',
        'secondary-fixed': '#a6f2d1',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary': '#ffffff',
        'surface-tint': '#006c49',
        'on-secondary-fixed': '#002116',
        'surface-container-highest': '#d3e7db',
        'inverse-surface': '#23342c',
        'on-error-container': '#93000a',
        background: '#eafef1',
        'on-tertiary-container': '#00367a',
        'on-tertiary-fixed-variant': '#004395',
        'error-container': '#ffdad6',
        'accent-orange': '#F97316',
        'on-accent-orange': '#FFFFFF',
        'gov-accent': '#8B5CF6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'form-stack': '16px',
        'container-padding': '32px',
        unit: '8px',
        'card-gap': '24px',
        'inline-sm': '8px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
