import Icon from '../Icon.jsx'

const ACTIVITIES = [
  {
    icon: 'description',
    iconClass: 'bg-secondary/10 text-secondary',
    text: (
      <>
        <span className="font-bold">Quarterly Emissions Report</span> was generated by Sarah Chen.
      </>
    ),
    meta: '2 hours ago • Environmental Module',
  },
  {
    icon: 'military_tech',
    iconClass: 'bg-tertiary/10 text-tertiary',
    text: (
      <>
        Global Operations reached <span className="font-bold">Zero-Waste Milestone</span>.
      </>
    ),
    meta: '5 hours ago • Gamification',
  },
  {
    icon: 'warning',
    iconClass: 'bg-error/10 text-error',
    text: (
      <>
        New <span className="font-bold">Compliance Directive</span> detected for EU Supply Chain.
      </>
    ),
    meta: 'Yesterday • Governance Module',
  },
]

const QUICK_ACTIONS = [
  {
    icon: 'add_circle',
    label: 'New Report',
    iconColor: 'text-primary',
    hover: 'hover:border-primary hover:bg-primary/5',
    hoverIcon: 'group-hover:text-primary',
  },
  {
    icon: 'rocket_launch',
    label: 'Start Challenge',
    iconColor: 'text-secondary',
    hover: 'hover:border-secondary hover:bg-secondary/5',
    hoverIcon: 'group-hover:text-secondary',
  },
  {
    icon: 'folder_open',
    label: 'View Reports',
    iconColor: 'text-tertiary',
    hover: 'hover:border-tertiary hover:bg-tertiary/5',
    hoverIcon: 'group-hover:text-tertiary',
  },
]

export default function ActivitySection() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-card-gap">
      {/* Recent Activity */}
      <div className="lg:col-span-2 glass-card rounded-xl overflow-hidden">
        <div className="p-6 border-b border-outline-variant flex justify-between items-center">
          <h3 className="text-headline-sm text-on-surface">Recent Activity</h3>
          <button className="text-primary text-label-md hover:underline">View History</button>
        </div>
        <div className="divide-y divide-outline-variant">
          {ACTIVITIES.map((a, i) => (
            <div key={i} className="p-6 flex gap-4 hover:bg-surface-variant/20 transition-colors">
              <div
                className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${a.iconClass}`}
              >
                <Icon name={a.icon} />
              </div>
              <div>
                <p className="text-body-md text-on-surface">{a.text}</p>
                <p className="text-label-sm text-on-surface-variant mt-1">{a.meta}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="space-y-card-gap">
        <div className="glass-card p-6 rounded-xl">
          <h3 className="text-headline-sm text-on-surface mb-6">Quick Actions</h3>
          <div className="grid grid-cols-1 gap-3">
            {QUICK_ACTIONS.map((action) => (
              <button
                key={action.label}
                className={`w-full flex items-center justify-between p-4 bg-surface-container-low border border-outline-variant rounded-xl group transition-all ${action.hover}`}
              >
                <div className="flex items-center gap-3">
                  <Icon name={action.icon} className={action.iconColor} />
                  <span className="text-label-md">{action.label}</span>
                </div>
                <Icon
                  name="chevron_right"
                  className={`text-outline-variant ${action.hoverIcon}`}
                />
              </button>
            ))}
          </div>
        </div>

        <div className="bg-primary p-6 rounded-xl text-white relative overflow-hidden group">
          <div className="relative z-10">
            <h4 className="text-headline-sm mb-2">Sustainability Pro</h4>
            <p className="text-body-sm opacity-90 mb-4">
              You've saved 4,200kg of CO2 this month. View your personal impact dashboard.
            </p>
            <button className="px-4 py-2 bg-white text-primary rounded-lg text-label-md hover:bg-primary-fixed transition-colors">
              Personal Stats
            </button>
          </div>
          <Icon
            name="nature"
            className="absolute -bottom-4 -right-4 text-9xl opacity-10 rotate-12 group-hover:rotate-0 transition-transform duration-500"
          />
        </div>
      </div>
    </div>
  )
}
