import { Link } from 'react-router-dom'
import Icon from '../Icon.jsx'

const ACTIVITIES = [
  {
    icon: 'description',
    iconClass: 'bg-gradient-to-br from-emerald-100 to-green-50 text-emerald-600',
    to: '/environmental',
    text: (
      <>
        <span className="font-semibold">Quarterly Emissions Report</span> was generated by Sarah Chen.
      </>
    ),
    meta: '2 hours ago • Environmental Module',
    dot: 'bg-emerald-500',
  },
  {
    icon: 'military_tech',
    iconClass: 'bg-gradient-to-br from-amber-100 to-yellow-50 text-amber-600',
    to: '/gamification',
    text: (
      <>
        Global Operations reached <span className="font-semibold">Zero-Waste Milestone</span>.
      </>
    ),
    meta: '5 hours ago • Gamification',
    dot: 'bg-amber-500',
  },
  {
    icon: 'warning',
    iconClass: 'bg-gradient-to-br from-red-100 to-rose-50 text-red-600',
    to: '/governance',
    text: (
      <>
        New <span className="font-semibold">Compliance Directive</span> detected for EU Supply Chain.
      </>
    ),
    meta: 'Yesterday • Governance Module',
    dot: 'bg-red-500',
  },
]

const QUICK_ACTIONS = [
  {
    icon: 'add_circle',
    label: 'New Report',
    desc: 'Generate ESG report',
    to: '/reports',
    gradient: 'from-emerald-100 to-green-50',
    iconColor: 'text-emerald-600',
  },
  {
    icon: 'rocket_launch',
    label: 'Start Challenge',
    desc: 'Launch sustainability challenge',
    to: '/gamification',
    gradient: 'from-amber-100 to-yellow-50',
    iconColor: 'text-amber-600',
  },
  {
    icon: 'folder_open',
    label: 'View Reports',
    desc: 'Access generated reports',
    to: '/reports',
    gradient: 'from-blue-100 to-indigo-50',
    iconColor: 'text-blue-600',
  },
]

export default function ActivitySection() {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-3 sm:gap-4">
      {/* Recent Activity */}
      <div className="lg:col-span-2 bg-white rounded-xl border border-black/[0.04] shadow-sm overflow-hidden">
        <div className="p-4 sm:p-5 border-b border-black/[0.04] flex justify-between items-center">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-slate-100 to-gray-50 flex items-center justify-center">
              <Icon name="history" className="text-[16px] text-slate-600" />
            </div>
            <h3 className="text-base font-bold text-on-surface">Recent Activity</h3>
          </div>
          <Link to="/reports" className="text-primary text-xs font-semibold hover:underline flex items-center gap-1 px-3 py-1.5 rounded-lg hover:bg-primary/5 transition-colors">
            View All
            <Icon name="arrow_forward" className="text-[14px]" />
          </Link>
        </div>
        <div className="divide-y divide-black/[0.03]">
          {ACTIVITIES.map((a, i) => (
            <Link
              key={i}
              to={a.to}
              className="p-4 sm:p-4.5 flex gap-3 hover:bg-black/[0.015] transition-colors focus:outline-none group"
            >
              <div
                className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ${a.iconClass}`}
              >
                <Icon name={a.icon} className="text-[18px]" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm text-on-surface leading-relaxed">{a.text}</p>
                <div className="flex items-center gap-1.5 mt-1">
                  <span className={`w-1.5 h-1.5 rounded-full ${a.dot}`} />
                  <p className="text-[11px] text-on-surface-variant/60">{a.meta}</p>
                </div>
              </div>
              <Icon name="chevron_right" className="text-on-surface-variant/0 group-hover:text-on-surface-variant/40 transition-colors self-center text-[16px]" />
            </Link>
          ))}
        </div>
      </div>

      {/* Quick Actions + Impact Card */}
      <div className="space-y-3 sm:space-y-4">
        <div className="bg-white p-4 sm:p-5 rounded-xl border border-black/[0.04] shadow-sm">
          <div className="flex items-center gap-2.5 mb-4">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary/10 to-emerald-50 flex items-center justify-center">
              <Icon name="bolt" className="text-[16px] text-primary" />
            </div>
            <h3 className="text-base font-bold text-on-surface">Quick Actions</h3>
          </div>
          <div className="grid grid-cols-1 gap-2.5">
            {QUICK_ACTIONS.map((action) => (
              <Link
                key={action.label}
                to={action.to}
                className="flex items-center gap-3 p-3 rounded-lg border border-black/[0.04] hover:border-primary/20 hover:shadow-sm group transition-all duration-200"
              >
                <div className={`w-9 h-9 rounded-lg bg-gradient-to-br ${action.gradient} flex items-center justify-center flex-shrink-0`}>
                  <Icon name={action.icon} className={`text-[18px] ${action.iconColor}`} />
                </div>
                <div className="flex-1 min-w-0">
                  <span className="text-sm font-semibold text-on-surface block">{action.label}</span>
                  <span className="text-[11px] text-on-surface-variant/60">{action.desc}</span>
                </div>
                <Icon
                  name="chevron_right"
                  className="text-on-surface-variant/15 group-hover:text-primary/50 transition-colors text-[16px]"
                />
              </Link>
            ))}
          </div>
        </div>

        {/* Impact card */}
        <div className="relative overflow-hidden p-5 rounded-xl bg-gradient-to-br from-[#1b5e3b] to-[#14532d] text-white shadow-md">
          {/* Decorative */}
          <div className="absolute -top-6 -right-6 w-28 h-28 bg-white/5 rounded-full blur-xl" />
          <div className="absolute -bottom-4 -left-4 w-20 h-20 bg-white/5 rounded-full" />

          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-7 h-7 rounded-md bg-white/15 flex items-center justify-center">
                <Icon name="nature" className="text-[16px] text-white/80" />
              </div>
              <span className="text-[11px] font-semibold uppercase tracking-wider text-white/60">Impact Score</span>
            </div>
            <h4 className="text-lg font-bold mb-1">Sustainability Pro</h4>
            <p className="text-xs text-white/60 mb-3.5 leading-relaxed">
              You've saved <span className="text-white font-bold">4,200kg</span> of CO2 this month.
            </p>
            <Link
              to="/gamification"
              className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-white/15 border border-white/15 text-white rounded-lg text-xs font-medium hover:bg-white/25 transition-colors"
            >
              View Stats
              <Icon name="arrow_forward" className="text-[14px]" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
